<?php 

// /home/rattandirect/public_html/app/design/frontend/rattandirect/default/template/checkout/cart/crosssell.phtml

$_helper = $this->helper('catalog/output');?>
<?php if($this->getItemCount()): ?>


<div class="featured-products crosssell-slider">
    <h2 class="feature-pro">Based on your selection, you might like to add</h2>
    <div id="category-products3">
        <?php foreach ($this->getItems() as $_product): ?>
            <div class="item">
                <div class="products-item" data-sku="<?php echo $_product->getSku(); ?>">
                          <?php
                        $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
                        $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
                        if ($_regularPrice != $_finalPrice):
                            $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
                        $finalpercentage = 100 - $getpercentage;
                        if ($finalpercentage > 0):
                            echo '<div class="b"><span>Save ' . number_format($finalpercentage, 0) . '%</span></div>';
                        endif;
                        endif;
                        if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE):

                            $_priceModel = $_product->getPriceModel();
                        list($_minimalPriceTax, $_maximalPriceTax) = $_priceModel->getTotalPrices($_product, null, null, false);
                        list($_minimalPriceInclTax, $_maximalPriceInclTax) = $_priceModel->getTotalPrices($_product, null, true, false);
                        $_Bundlefinal = number_format((float) $_minimalPriceInclTax, 2, '.', '');
                        $_bundleRRP = $_product->getbundleorgprice();
                        $_bundleRRP2 = preg_replace('/[^0-9]/', '', $_bundleRRP);
                        $_perccal1 = $_bundleRRP2 - $_Bundlefinal;
                        $_perccal2 = $_perccal1 / $_bundleRRP2;
                        $_perccal3 = number_format($_perccal2 * 100, 2);
                        if ($_perccal3 > 0):
                            echo '<div class="b"><span>Save ' . number_format($_perccal3, 0) . '%</span></div>';
                        endif;
                        endif;
                        ?>
                    <div class="amlabel-div">
                        <?php echo Mage::helper('amlabel')->getLabels($_product) ?>
                    <a href="<?php echo $this->getBaseUrl() . $_product->getUrlKey() . ".htmll#_s=cs" ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300,226);?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                        <div class="label-product">
                            <?php if ($_product->getData('new')) {
                                echo '<span class="new">' . $this->__('New') . '</span>';
                            } ?>
    <?php if ($_product->getData('sale')) {
        echo '<span class="sale">' . $this->__('Sale') . '</span>';
    } ?>
                        </div>
                    </a>
                    </div>
                    <div class="product-shop">
                        <div class="product-name"><?php $this->helper('yotpo')->showBottomline($this, $_product); ?><a href="<?php echo $this->getBaseUrl() . $_product->getUrlKey() . ".html#_s=cs" ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a></div>

    <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>

                        <div class="actions">
                                        <?php if ($_product->getneeds_customisation()): ?>
                                <button type="button" title="<?php echo $this->__('View') ?>" class="button btn-details" onclick="setLocation('<?php echo $this->getBaseUrl() . $_product->getUrlKey() . ".html" ?>')"><span><span><i class="fa fa-eye" aria-hidden="true"></i>
                                <?php echo $this->__('View') ?></span></span></button>
                            <?php else : ?>
                                <button type="button" title="<?php echo $this->__('View') ?>" class="button btn-details" onclick="setLocation('<?php echo $this->getBaseUrl() . $_product->getUrlKey() . ".html" ?>')"><span><span><i class="fa fa-eye" aria-hidden="true"></i>
                                <?php echo $this->__('View') ?></span></span></button>
                            <?php endif; ?>
                            <?php if ($_product->isSaleable()): ?>
                                <?php if ($_product->getneeds_customisation()): ?>
                                    <button type="button" title="<?php echo $this->__('Customise') ?>" class="button btn-cart"onclick="setLocation('<?php echo $this->getBaseUrl() . $_product->getUrlKey() . ".html" ?>')"><span><span><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php echo $this->__('Customise') ?></span></span></button>
                                <?php else : ?>
                                    <?php
                                    $productAddUrl = $this->helper('checkout/cart')->getAddUrl($_product);
                                    if ($_product->getTypeId() == 'bundle'):
                                        $bundleOptions = '?';
                                        $selectionCollection = $_product->getTypeInstance(true)->getSelectionsCollection($_product->getTypeInstance(true)->getOptionsIds($_product), $_product);
                                        foreach ($selectionCollection as $option):
                                            $bundleOptions .= '&bundle_option[' . $option->option_id . ']=' . $option->selection_id;
                                            $bundleOptions .= '&bundle_option_qty[' . $option->option_id . ']=' . $option->selection_qty;
                                        endforeach;
                                        $productAddUrl .= $bundleOptions;
                                    endif;
                                    ?>
                                    <button type="button" title="<?php echo $this->__('Add to Basket') ?>" class="button btn-cart" onclick="setLocation('<?php echo $productAddUrl ?>')"><span><span><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php echo $this->__('Add to Basket') ?></span></span></button>
        <?php endif; ?>
    <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>


                        </div>
                    </div>
                </div>
            </div>

<?php endforeach ?>
    </div>

</div>
 
<?php endif; ?>
<script type="text/javascript">
    $crosli = jQuery.noConflict();
    $crosli(document).ready(function() {
        $crosli("#category-products3").owlCarousel({
            dots :false,
            loop:false,
            navText: [
                "<i class='fa fa-long-arrow-left' aria-hidden='true'></i>",
                "<i class='fa fa-long-arrow-right'  aria-hidden='true'></i>"
            ],
            responsive:{
                0:{
                    items:1,
                    <?php if(count($this->getItems()) > 1): ?> nav:true <?php else: ?>nav:false <?php endif; ?>            
                },
                768:{
                    items:2,
                    <?php if(count($this->getItems()) > 2): ?> nav:true <?php else: ?>nav:false <?php endif; ?>
                },
                992:{
                    items:3,
                    <?php if(count($this->getItems()) > 3): ?> nav:true <?php else: ?>nav:false <?php endif; ?>
                },
                1200:{
                    items:4,
                    <?php if(count($this->getItems()) > 4): ?> nav:true <?php else: ?>nav:false <?php endif; ?>
                }
            },
        });
    });
</script>



